<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchProductCount() {

        $queryBuilder = $this->createQueryBuilder('u');

        return $queryBuilder
                ->select($queryBuilder->expr()->count('u'))
                ->getQuery()->getSingleScalarResult();

    }

    /**
     *
     * @param $current_page 0...n
     * @param $num_result 10
     */
    public function  fetchUserPaginated($current_page, $num_result) {

        $current_page--;

        $qb = $this->createQueryBuilder('u');
        $qb->select('u')
            ->setFirstResult($current_page * $num_result)
            ->setMaxResults($num_result);

        return $qb->getQuery()->getResult();
    }

}

