<?php

namespace AppBundle\Repository;

/**
 * CartCarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCarsRepository extends \Doctrine\ORM\EntityRepository
{
}
