<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function fetchBiggestPromotion() {
        $qb = $this->createQueryBuilder('p');
        
        $today = (new \DateTime())->setTime(0, 0, 0);
        
        $query = $qb->select('p.percent')
            ->where($qb->expr()->lte('p.startDate', ':today'))
            ->andWhere($qb->expr()->gte('p.endDate', ':today'))
            ->setParameter(':today', $today)
            ->orderBy('p.percent', 'DESC')
            ->setMaxResults(1)
            ->getQuery();
        
        if ($query->getOneOrNullResult() !== null) {
            return $query->getSingleScalarResult();
        }
        
        return 0;
    }
    
}
