<?php

$this->extend('layout');

$postUrl = isset($this->employee)
           ? '?controller=employee&action=edit&id=' . $this->employee['id']
           : '?controller=employee&action=add';

?>

<div class="employee">
    <h1><?php echo isset($this->employee) ? 'Редактиране' : 'Добавяне' ?> на служител</h1>
    <form id="employee-add" method="POST" action="<?php echo $postUrl; ?>">
        <div>
            <label>Име</label>
            <input type="text" name="first_name" value="<?php echo get_value('first_name', $this->data); ?>" />
            <?php echo show_errors('first_name', $this->errors); ?>
        </div>
        <div>
            <label>Презиме</label>
            <input type="text" name="middle_name" value="<?php echo get_value('middle_name', $this->data); ?>" />
            <?php echo show_errors('middle_name', $this->errors); ?>
        </div>
        <div>
            <label>Фамилия</label>
            <input type="text" name="last_name" value="<?php echo get_value('last_name', $this->data); ?>" />
            <?php echo show_errors('last_name', $this->errors); ?>
        </div>
        <div>
            <label>Адрес</label>
            <input type="text" name="address" value="<?php echo get_value('address', $this->data); ?>" />
            <?php echo show_errors('address', $this->errors); ?>
        </div>
        <div>
            <label>Телефон</label>
            <input type="text" name="phone" value="<?php echo get_value('phone', $this->data); ?>" />
            <?php echo show_errors('phone', $this->errors); ?>
        </div>
        <div>
            <label>Отдел</label>
            <select name="department_id"><?php echo build_оptions($this->departments, get_value('department_id', $this->data), 'Избери'); ?></select>
            <?php echo show_errors('department_id', $this->errors); ?>
        </div>
        <div>
            <label>Длъжност</label>
            <select name="position_id"><?php echo build_оptions($this->positions, get_value('position_id', $this->data), 'Избери'); ?></select>
            <?php echo show_errors('position_id', $this->errors); ?>
        </div>
        <div>
            <label>Заплата (лв.)</label>
            <input type="text" name="salary" value="<?php echo get_value('salary', $this->data, 0); ?>" />
            <?php echo show_errors('salary', $this->errors); ?>
        </div>
        <div>
            <input type="submit" name="btnSave" value="Запазване" />
        </div>
    </form>
</div>