<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Задача</title>
    <link href="assets/css/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="content">
        <?php if (($identity = Solver\Auth::getInstance()->getIdentity()) !== null) : ?>
        <div>Добре дошъл <?php echo $identity['name']; ?> (<?php echo $identity['email']; ?>)</div>
        <ul class="nav">
            <li><a href="?controller=home">Начало</a></li>
            <li><a href="?controller=employee&action=add">Добавяне на служител</a></li>
            <li><a href="?controller=logout">Изход</a></li>
        </ul>
        <?php endif; ?>
        <?php
        if (($flash = flash()) !== '') :
            echo '<div class="message">' . $flash . '</div>';
        endif;
        ?>
        <?php echo $this->show('content'); ?>
    </div>
    <script type="text/javascript" src="assets/js/jquery.js"></script>
    <script type="text/javascript" src="assets/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="assets/js/main.js"></script>
</body>
</html>