<?php

namespace AppBundle\Repository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchModel() {

        $qb = $this->createQueryBuilder('m');
        $qb->select('m.id, m.mark_id, m.name');

        return $qb->getQuery()->getResult();

    }

    public function fetchModelById($id) {

        $qb = $this->createQueryBuilder('m');
        $qb->select('m.name')
        ->where('m.id = ' . $id);

        return $qb->getQuery()->getResult();

    }

}
