<?php $this->extend('layout'); ?>

<h1>Списък със служители</h1>
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Дата</th>
            <th>Име</th>
            <th>Презиме</th>
            <th>Фамилия</th>
            <th>Адрес</th>
            <th>Телефон</th>
            <th>Отдел</th>
            <th>Длъжност</th>
            <th>Заплата</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $item) : ?>
        <tr>
            <td><a href="?controller=employee&action=edit&id=<?php echo $item['id']; ?>"><?php echo $item['id']; ?></a></td>
            <td><?php echo $item['created']; ?></td>
            <td><?php echo $item['first_name']; ?></td>
            <td><?php echo $item['middle_name']; ?></td>
            <td><?php echo $item['last_name']; ?></td>
            <td><?php echo $item['address']; ?></td>
            <td><?php echo $item['phone']; ?></td>
            <td><?php echo isset($this->departments[$item['department_id']]) ? $this->departments[$item['department_id']] : ''; ?></td>
            <td><?php echo isset($this->positions[$item['position_id']]) ? $this->positions[$item['position_id']] : ''; ?></td>
            <td><?php echo $item['salary']; ?> лв.</td>
            <td class="text-center"><a class="remove" href="?controller=employee&action=delete&id=<?php echo $item['id']; ?>">x</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>