<?php $this->extend('layout'); ?>

<div class="login">
    <form id="login" method="POST" action="?controller=login">
        <div>
            <input type="text" name="username" placeholder="и-мейл" value="<?php echo get_value('username', $this->data); ?>" />
            <?php echo show_errors('username', $this->errors); ?>
        </div>
        <div>
            <input type="password" name="password" placeholder="парола" />
            <?php echo show_errors('password', $this->errors); ?>
        </div>
        <div>
            <input type="submit" name="btnLogin" value="Вход" />
            <?php echo show_errors('login', $this->errors); ?>
        </div>
    </form>
    <div>user: root@root.bg</div>
    <div>pass: 123456</div>
</div>